---
appveyor.yml:
  matrix:
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21-x64
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 23
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 23-x64
spec/spec_helper.rb:
  allow_deprecations: true
